import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

import type { Medication, PetSummary } from '../types';
import { formatDateInputInTimeZone } from '../utils/dateTime';

function escapeHtml(value: unknown) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function row(label: string, value?: string | number | null) {
  if (value === null || value === undefined || String(value).trim() === '') return '';
  return `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value)}</td></tr>`;
}

export async function shareEmergencyPetCard(
  pet: PetSummary,
  medications: Medication[],
  timeZone = 'UTC'
) {
  if (!(await Sharing.isAvailableAsync())) {
    throw new Error('PDF sharing is not available on this device.');
  }

  const today = formatDateInputInTimeZone(new Date(), timeZone);
  const currentMedicationText = medications
    .filter(
      (item) =>
        item.is_active &&
        !item.paused_at &&
        (!item.start_date || item.start_date <= today) &&
        (!item.end_date || item.end_date >= today)
    )
    .map((item) => {
      const amount = [item.dose, item.unit].filter(Boolean).join(' ');
      return `${item.name}${amount ? ` — ${amount}` : ''}${
        item.instructions ? ` (${item.instructions})` : ''
      }`;
    })
    .join('; ');

  const html = `<!doctype html>
  <html><head><meta charset="utf-8" />
  <style>
    body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#1f2a27;padding:36px}
    .brand{color:#53166f;font-weight:800;font-size:18px}.title{font-size:34px;margin:10px 0 4px}
    .subtitle{color:#5b6863;margin-bottom:24px}.warning{background:#fff4dc;border-radius:12px;padding:14px;margin:20px 0}
    table{border-collapse:collapse;width:100%}th,td{padding:10px 8px;border-bottom:1px solid #dde4e0;text-align:left;vertical-align:top}
    th{width:34%;color:#53615c}.foot{font-size:11px;color:#68746f;margin-top:26px}
  </style></head><body>
    <div class="brand">PAWSO EMERGENCY CARD</div>
    <h1 class="title">${escapeHtml(pet.name)}</h1>
    <div class="subtitle">${escapeHtml(pet.species === 'cat' ? 'Cat' : 'Dog')}${
      pet.breed ? ` · ${escapeHtml(pet.breed)}` : ''
    }</div>
    <div class="warning"><strong>For emergencies:</strong> contact a veterinarian or emergency clinic. This card is a handoff summary, not medical advice.</div>
    <table>
      ${row('Date of birth', pet.date_of_birth || pet.approximate_age)}
      ${row('Sex', pet.sex)}
      ${row('Weight', pet.weight_kg ? `${pet.weight_kg} kg` : null)}
      ${row('Microchip', pet.microchip_number)}
      ${row('Conditions', pet.conditions)}
      ${row('Allergies', pet.allergies)}
      ${row('Current scheduled medications', currentMedicationText)}
      ${row('Other medication notes', pet.medications)}
      ${row('Veterinary clinic', pet.vet_clinic)}
      ${row('Emergency contact', pet.emergency_contact_name)}
      ${row('Emergency phone', pet.emergency_contact_phone)}
      ${row('Emergency notes', pet.emergency_notes)}
    </table>
    <div class="foot">Generated by Pawso on ${escapeHtml(new Date().toLocaleString())}. Verify details with the pet owner and veterinarian.</div>
  </body></html>`;

  const { uri } = await Print.printToFileAsync({ html });
  try {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
      dialogTitle: `Share ${pet.name}'s emergency card`,
    });
  } finally {
    await FileSystem.deleteAsync(uri, { idempotent: true }).catch(() => undefined);
  }
}
